name: Stable release
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: instal node dependencies
      run: npm install

    - name: Change to production mode
      run: npm run prod

    - name: Compile and minify the code
      run: npm run dist
    
    - name: Remove gitignore
      run: rm .gitignore
      
    - name: Check the output
      run: ls -lha web/styles/ && ls -lha client/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
